### ISSUE TITLE
Morning Study Hall 2018-03-01

### ISSUE THREAD

**Issue by zgulde** [CodeupClassroom/study-halls#1]
Comment here with any questions you have that you want to talk about friday morning.

Code samples are highly encouraged!

**Comment by bettinatrejo** [comment]
Can we go over recursion? (When to use it?)
Specifically the curriculum example.

**Example:**
public static long getPower(int base, int exponent) {
    long result = 1;
    for (int i = 1; i <= exponent; i++) {
        result = result * base;
    }
    return result;
}

**Refactor to use recursion**

public static long getPower(int base, int exponent) {
    if (exponent == 0) {
        return 1;
    } else if (exponent == 1) {
        return base;
    } else if (exponent == 2) {
        return base * base;
    }
    return base * getPower(base, exponent - 1);
}

**Comment by emmaldejong** [comment]
Could we review the printf () method? I'm just not understanding the format specifiers(?) for the method. Here is a link to some of the information I was trying to follow: [https://alvinalexander.com/programming/printf-format-cheat-sheet]

How is printf () different from the String.format () method?

Here is my code from the Table of Powers exercise where my questions about these came up:
Scanner scanner = new Scanner(System.in);
        boolean confirmCont = true;

            do {
                System.out.print("Please enter a number: ");
                int input = scanner.nextInt();

                System.out.println("number | squared | cubed");
                System.out.println("------ | --------| ------");

                for (int i = 1; i <= input; i += 1) {
                    String output = "";
                    output += String.format("%-7d", i);
                    output += String.format("|%-9d", i * i);
                    output += String.format("|%d", i * i * i);
                    System.out.println(output);
                }

                System.out.print("Continue? [y/n]");
                String userChoice = scanner.next();
                if (userChoice.equalsIgnoreCase("y") || userChoice.equalsIgnoreCase("yes")) {
                    confirmCont = true;
                } else {
                    confirmCont = false;
                }

            } while (confirmCont);

**Comment by emmaldejong** [comment]
Could we review the Java data types? I think I understand them, I just get confused by what the description in the attached screenshot means. Maybe I just need a more simple way of defining them.

<img width="902" alt="screen shot 2018-03-01 at 4 10 48 pm" src="https://user-images.githubusercontent.com/35229956/36873436-1bb0aba4-1d6e-11e8-8323-95c206a5ba3f.png">

**Comment by emmaldejong** [comment]
**Questions if we have time:**

1) Implicit v. Explicit casting: I just needed some clarification, Implicit casting is taking a "wider" data type for a variable and making it more precise while Explicit casting is taking a "narrow" data type of a variable and making it less precise/wider? (Is this statement correct: _It's easier to make variables more precise in Java than it is to "widen" their data type scope._)

2) _Method Overloading is a way of defining multiple methods with the same name but with different type/order/count. In order to overload a method it needs to always have the same amount of parameters._
Can you explain this maybe with an example? Maybe I just don't understand it because I haven't used it in practice yet.
```
public class DataArtist {
    ...
    public void draw(String s) {
        ...
    }
    public void draw(int i) {
        ...
    }
    public void draw(double f) {
        ...
    }
    public void draw(int i, double f) {
        ...
    }
}
```

3) Do the "class files types" that we are using in IntelliJ right now for our exercises have any relation to Classes in Java, like the Class v. Object structure?
